sudo: required
services:
  - docker
language: go
go:
  - "1.8"

before_install:
  - "env"
  - "echo $TRAVIS_BRANCH"
  - "git rev-parse --abbrev-ref HEAD"
install:
  - ":" # do nothing
script:
  - ./docker-build-all.sh
