version: '2'
services:
    mysql: # MySQL
        restart: always
        volumes:
            - mysql-volume:/var/lib/mysql
        image: mysql
        user: mysql
        command: 
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment: 
            MYSQL_ROOT_PASSWORD: ${PP_DB_PASSWORD}
            MYSQL_DATABASE: popcon
    
    redis:
        restart: always
        image: redis
        entrypoint: 
            - redis-server
            - --requirepass
            - ${PP_DB_PASSWORD}
    mongo:
        restart: always
        image: mongo

    ppdata:
        image: busybox
        volumes: 
            - ./pp_data:/data
        
    sendmail:
        build: ./modules/sendmail

    # ランキング/ジャッジコントローラ
    ppjc:
        image: ppjc
        ports:
            - 5050:80
        environment:
            PP_MYSQL_ADDR: "root:${PP_DB_PASSWORD}@tcp(mysql:3306)/popcon?charset=utf8mb4&parseTime=True"
            PP_REDIS_ADDR: "redis:6379"
            PP_REDIS_PASS: "${PP_DB_PASSWORD}"
            PP_MONGO_ADDR: "mongo:27017"
            PP_MS_ADDR: "http://ppms:7502"
            PP_TOKEN: ${PP_TOKEN}
            PP_DEBUG_MODE: 1

    ppms:
        image: ppms
        environment:
            PP_MONGO_ADDR: "mongo:27017"
            PP_TOKEN: ${PP_TOKEN}

    # Webサーバ
    ppweb:
        image: ppweb
        volumes_from:
            - sendmail
        ports: 
            - 1234:80
        environment:
            PP_MYSQL_ADDR: "root:${PP_DB_PASSWORD}@tcp(mysql:3306)/popcon?charset=utf8mb4&parseTime=True"
            PP_REDIS_ADDR: "redis:6379"
            PP_REDIS_PASS: "${PP_DB_PASSWORD}"
            PP_MONGO_ADDR: "mongo:27017"
            PP_JC_ADDR: "http://ppjc"
            PP_MS_ADDR: "http://ppms:7502"
            PP_TOKEN: ${PP_TOKEN}
            PP_LISTEN: ":80"
            PP_DEBUG_MODE: 1
volumes:
    mysql-volume:
        driver: local
